version: '3'

services:
  my-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
    ports:
      - "15432:5432"
    volumes:
      - /home/eric/desenvolvimento/docker:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  my-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "dev@trinusco.com.br"
      PGADMIN_DEFAULT_PASSWORD: "devPass2021!"
    ports:
      - "16543:80"
    depends_on:
      - my-postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge